/*
 * File: PreviewFrame.java
 * Creation: 09.06.2010
 * Author: Hj. Malthaner <h_malthaner@users.sourceforge.net>
 * License: See license.txt
 */

package tilemaster.editor.ui;

import java.awt.Color;
import java.awt.Image;

/**
 *
 * @author Hj. Malthaner
 */
public class PreviewFrame extends javax.swing.JFrame
{
    private TilingPreview tilingPreview;

    public void setIsometric(boolean isIso)
    {
        tilingPreview.setIsometric(isIso);
    }

    public void setCursorPosition(int tileX, int tileY)
    {
        tilingPreview.setCursorPosition(tileX, tileY);
    }

    public void setImage(Image img)
    {
        tilingPreview.setImage(img);
        repaint();
    }

    public void setRaster(int w, int h)
    {
        tilingPreview.setRaster(w, h);
    }

    @Override
    public void setBackground(Color c) 
    {        
        super.setBackground(c);
        
        if(tilingPreview != null) 
        {
            tilingPreview.setBackground(c);
        }
    }



    /** Creates new form PreviewFrame */
    public PreviewFrame()
    {
        initComponents();

        tilingPreview = new TilingPreview();

        getContentPane().add(tilingPreview);

        setSize(400, 300);
        setLocation(800, 10);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tiling Preview");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreviewFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
